### ISSUE TITLE
搞不懂配置哪个module,哪个controller

### ISSUE THREAD

**Issue by akzhou** [akira-cn/think-wechat#7]
搞不懂配置哪个module,哪个controller,懵逼了。。

**Comment by akira-cn** [comment]
默认是 home/wechat 这个你可以在 config 里配置的，如果你微信开发者中心里的开发服务器 url 配置成 `http://你的域名/wechat`，那么就不用改配置。然后你在微信公众号里发送一段文本，就会落在 home/wechat/text，发送一段语音，就会落在 home/wechat/voice。。。所以你就写对应的 textAction、voiceAction。。。就可以了
