### ISSUE TITLE
能否提供个完整的配置流程

### ISSUE THREAD

**Issue by haodalong** [akira-cn/think-wechat#8]
您好，我的thinkjs版本是2.2，折腾了半天也没有搞定，问题如下：
第一张图是middleware的配置：
![image](https://user-images.githubusercontent.com/13931187/29260542-148c1556-80fd-11e7-9089-28b3e0871797.png)
第二张图是controller里的配置：
![image](https://user-images.githubusercontent.com/13931187/29260548-1d9f6864-80fd-11e7-98cf-28a8ede65a43.png)
我这样配置了以后为什么微信发信息，还是在wechat而不是在wechat/text接收到？

**Comment by akira-cn** [comment]
2.x 和 3.0 的配置是不同的，2.x 请切换到这个分支 ： https://github.com/akira-cn/think-wechat/tree/2.0 按照这上面的说明来配置。
